#spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm:
#  admin-user:
#    id: admin
#    password: admin
  deployment-resource-pattern:
    - classpath*:**/*.bpmn
    - classpath*:**/*.bpmn20.xml
    - classpath*:**/*.dmn
    - classpath*:**/*.dmn11.xml
    - classpath*:**/*.form
  database:
      type: postgres
server:
  port: '8083'
spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driverClassName: org.postgresql.Driver
    #DB connection:
    url: jdbc:postgresql://localhost:5432/temp_base
    username: postgres
    password: postgres
camunda:
  bpm:
    authorization:
      enabled: true
      tenant-check-enabled: false
  run:
    auth:
      enabled: true
#  generic-properties:
#    properties:
#      default-user-permission-name-for-task: TASK_WORK