#spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm:
#  admin-user:
#    id: admin
#    password: admin
  deployment-resource-pattern:
    - classpath*:**/*.bpmn
    - classpath*:**/*.bpmn20.xml
    - classpath*:**/*.dmn
    - classpath*:**/*.dmn11.xml
    - classpath*:**/*.form
  database:
      type: postgres
server:
  port: '8083'
spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driverClassName: org.postgresql.Driver
    #DB connection:
    url: jdbc:postgresql://10.1.10.17:5432/cam_develop
    username: cam_admin
    password: cam_admin_password
camunda:
  bpm:
    authorization:
      enabled: false
      tenant-check-enabled: false
    filter:
      create: All
  run:
    auth:
      enabled: false
#  generic-properties:
#    properties:
#      default-user-permission-name-for-task: TASK_WORK
logging:
  level:
    org.zalando.logbook: TRACE

gtm:
  user: admin
  pwd: Qwerty123
  auth-url: http://gtm-back:8080

springdoc:
  swagger-ui:
    path: /docs/swagger-ui

